### ISSUE TITLE
[BUG] Add support for GTX 10XX series

### ISSUE THREAD

**Issue by AzzaltoMusic** [IAHispano/Applio#249]
GPU not detected, reverting to CPU (not recommended)
Starting training...

 
![Screenshot_5](https://github.com/IAHispano/Applio/assets/152920603/258c8ec5-80e3-457a-a4be-be9a77421ee2)
![Screenshot_6](https://github.com/IAHispano/Applio/assets/152920603/eb737d8c-6db4-49af-839d-7766690d601d)

**Comment by mikhail2013ru** [comment]
There is no nvidia graphics card on my laptop, only an intel 11400 processor. Is it possible to add the ability to train a voice model on an integrated intel uhd 730 graphics card? We are also interested in the possibility of interrupting and resuming training at a convenient time while working on a laptop.

**Comment by blaise-tk** [comment]
Cannot train with GTX series CPU or GPU

The GTX series can be investigated, but it would be very slow

**Comment by AzzaltoMusic** [comment]
in RVC work well

**Comment by aitronssesin** [comment]
Also check if you have the latest driver version (Applio uses cuda toolkit 12.1)

https://docs.nvidia.com/deeplearning/cudnn/reference/support-matrix.html

**Comment by aitronssesin** [comment]
We've noticed that there hasn't been any activity or response on this issue for quite some time now. Due to the lack of engagement, we've decided to proceed with closing it. If you still encounter this problem or have any further input, please feel free to reopen the issue or create a new one. Thank you for your understanding.
