### ISSUE TITLE
[BUG] Applio Fails to Launch Post-Update on macOS (Apple Silicon) Due to omegaconf==2.0.5 Installation Error

### ISSUE THREAD

**Issue by jet3004** [IAHispano/Applio#635]
**Bug Description**
Have used Apple successfully for months but, after updating Applio yesterday, it will no longer launch on my Mac (Apple Silicon). The issue arises during the installation of dependencies from the `requirements.txt` file, specifically when attempting to install `omegaconf==2.0.5`. The following error occurs:

```
Collecting omegaconf==2.0.5 (from -r requirements.txt (line 23))
  Using cached omegaconf-2.0.5-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata:
Requested omegaconf==2.0.5 from https://files.pythonhosted.org/packages/e5/f6/043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl (from -r requirements.txt (line 23)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Ignored the following yanked versions: 1.0.0, 1.0.1, 1.0.2, 2.0.0rc1, 2.0.0rc2, 2.0.0rc22, 2.0.0rc23, 2.0.0rc24, 2.0.0rc25, 2.0.0rc26, 2.0.0rc27, 2.0.1rc1, 2.0.1rc2, 2.0.1rc3, 2.0.1rc4, 2.0.1rc5, 2.2.0
ERROR: Ignored the following versions that require a different python version: 1.14.0 Requires-Python >=3.10; 1.14.0rc1 Requires-Python >=3.10; 1.14.0rc2 Requires-Python >=3.10; 1.14.1 Requires-Python >=3.10; 2.1.0 Requires-Python >=3.10; 2.1.0rc1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement omegaconf==2.0.5 (from versions: 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.16, 1.0.17, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.2.0, 1.2.1, 1.3.0rc1, 1.3.0rc2, 1.3.0rc3, 1.3.0rc4, 1.3.0rc5, 1.3.0rc6, 1.3.0rc7, 1.3.0rc8, 1.3.0rc9, 1.3.0rc10, 1.3.0, 1.4.0rc1, 1.4.0rc2, 1.4.0rc3, 1.4.0, 1.4.1rc1, 1.4.1, 2.0.0rc3, 2.0.0rc4, 2.0.0rc5, 2.0.0rc6, 2.0.0rc7, 2.0.0rc8, 2.0.0rc9, 2.0.0rc10, 2.0.0rc11, 2.0.0rc12, 2.0.0rc13, 2.0.0rc14, 2.0.0rc15, 2.0.0rc16, 2.0.0rc17, 2.0.0rc18, 2.0.0rc19, 2.0.0rc20, 2.0.0rc21, 2.0.0, 2.0.1rc6, 2.0.1rc7, 2.0.1rc8, 2.0.1rc9, 2.0.1rc10, 2.0.1rc11, 2.0.1rc12, 2.0.1rc13, 2.0.1, 2.0.2rc1, 2.0.2rc2, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.1.0.dev1, 2.1.0.dev2, 2.1.0.dev3, 2.1.0.dev4, 2.1.0.dev5, 2.1.0.dev6, 2.1.0.dev7, 2.1.0.dev8, 2.1.0.dev9, 2.1.0.dev10, 2.1.0.dev11, 2.1.0.dev12, 2.1.0.dev13, 2.1.0.dev14, 2.1.0.dev15, 2.1.0.dev16, 2.1.0.dev17, 2.1.0.dev18, 2.1.0.dev19, 2.1.0.dev20, 2.1.0.dev21, 2.1.0.dev22, 2.1.0.dev23, 2.1.0.dev24, 2.1.0.dev25, 2.1.0.dev26, 2.1.0.dev27, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0.dev1, 2.2.0.dev2, 2.2.0.dev3, 2.2.0.dev4, 2.2.0.dev5, 2.2.1, 2.2.2, 2.3.0.dev0, 2.3.0.dev1, 2.3.0.dev2, 2.3.0, 2.4.0.dev0, 2.4.0.dev1, 2.4.0.dev2, 2.4.0.dev3)
ERROR: No matching distribution found for omegaconf==2.0.5
```

**Steps to Reproduce**
1. Update Applio to the latest version.
2. Attempt to launch the application.
3. If unsuccessful, try to rebuild the environment and install dependencies from `requirements.txt`.
4. Observe the errors during the installation, particularly with `omegaconf`.

**Expected Behavior**
Applio should launch successfully after the update, with all dependencies installing without errors.

**Assets**
No screenshots or videos, but the full error log is provided above.

**Desktop Details:**
- Operating System: macOS (Apple Silicon)
- Browser: N/A (issue is with a local application)

**Additional Context**
I have tried downgrading `pip` and rebuilding the environment multiple times with no success. I also found a potentially related issue in a recent pull request [here](https://github.com/IAHispano/Applio/pull/584), which suggests a fix was implemented, but I am still encountering the same issue after updating to the latest commit, so I feel this might be known but not sure why I keep going in this loop, thanks!

**Comment by blaisewf** [comment]
@Anthonyxd22

**Comment by i-sumin** [comment]
Hello,

I recently faced the same `omegaconf` dependency issue that you're encountering, but I was able to resolve it with the following steps. I'm now successfully running Applio.

### I installed Python 3.9 using Homebrew and created a virtual environment with Venv.
```
python3.9 -m venv .venv
source .venv/bin/activate
```
### I used `pip` version 23.0.1.
(The reason I downgraded the pip version was to install `omegaconf==2.0.5`. I don't know about other pip versions because I didn't check them.)
```
pip install pip==23.0.1
pip install -r requirements.txt
```
### I modified the `certifi` package version in the `requirements.txt` file.
```
certifi>=2023.07.22; sys_platform == 'darwin'
```

(The issue arises due to conflicting version requirements for the `certifi` package in the `requirements.txt` file. Specifically:

- The `requests` package requires `certifi>=2017.4.17`.
- The `edge-tts` package explicitly requires `certifi==2023.07.22`.
- However, the `requirements.txt` file specifies `certifi==2024.7.4`.

These conflicting requirements cause a dependency resolution conflict because `pip` cannot satisfy all three conditions simultaneously. The `requests` package allows for any `certifi` version above 2017.4.17, but `edge-tts` strictly requires the 2023.07.22 version. When you enforce `certifi==2024.7.4`, it overrides these requirements, leading to an unsolvable conflict.

To resolve this, you would need to adjust the `certifi` version in the `requirements.txt` to a range that satisfies all dependencies or remove the explicit version requirement to allow `pip` to choose the most appropriate version.)


After applying these changes, I ran `./run-applio.sh` in the terminal, and the Applio page opened successfully.

Also, I'm not a developer so it's not my area of ​​expertise and I'm not sure if this will help you, but I hope this helps you out.
